name: Sync Fork
on:
  schedule:
    - cron: '0 0 1 * *' # every month
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.SYNC_FORK_TOKEN }}
          base: master
          head: master
          retries: 5
          retry_after: 60
